export const cards = [
  {
    id: 1,
    title: "CA",
    desc: "Auditing",
    img: "https://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
  },
  {
    id: 2,
    title: "CS",
    desc: "LLP Registration",
    img: "https://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
  },
  {
    id: 3,
    title: "CA",
    desc: "Bussiness Setup",
    img: "https://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
  },
  {
    id: 4,
    title: "CA",
    desc: "Funding",
    img: "https://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
  },
  {
    id: 5,
    title: "CS",
    desc: "Compliences",
    img: "https://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
  },
  {
    id: 6,
    title: "CS",
    desc: "Tax",
    img: "https://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
  },
  {
    id: 7,
    title: "CA",
    desc: "Company Law",
    img: "https://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
  },
  {
    id: 8,
    title: "CS",
    desc: "Accounting",
    img: "hhttps://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
  },
];

export const projects = [
  {
    id: 1,
    img: "https://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
    pp: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "ROC Filings",

    username: "Anna Bell",
  },
  {
    id: 2,
    img: "https://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
    pp: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "IT return filing services",
    username: "Morton Green",
  },
  {
    id: 3,
    img: "https://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
    pp: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "International Taxation",
    username: "Emmett Potter",
  },
  {
    id: 4,
    img: "https://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
    pp: "https://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
    cat: "Bussiness Consultation",
    username: "Freddie Johnston",
  },
  {
    id: 5,
    img: "https://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
    pp: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Audit ",
    username: "Audrey Richards",
  },
  {
    id: 6,
    img: "https://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
    pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Tax",
    username: "Dalton Hudson",
  },
  {
    id: 7,
    img: "https://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
    pp: "https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Accounting",
    username: "Hannah Dougherty",
  },
  {
    id: 8,
    img: "https://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
    pp: "https://images.pexels.com/photos/1680175/pexels-photo-1680175.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Law",
    username: "Ward Brewer",
  },
];

export const services = [
  {
    id: 1,
    img: "https://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
    pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, quisquam.",
    price: 59,
    star: 5,
    username: "Anna Bell",
  },
  {
    id: 2,
    img: "https://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
    pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, quisquam.",
    price: 79,
    star: 5,
    username: "Lannie Coleman",
  },
  {
    id: 3,
    img: "https://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
    pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, quisquam.",
    price: 112,
    star: 5,
    username: "Carol Steve",
  },
  {
    id: 4,
    img: "https://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
    pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, quisquam.",
    price: 99,
    star: 4,
    username: "Don Weber",
  },
  {
    id: 5,
    img: "https://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
    pp: "https://images.pexels.com/photos/1771383/pexels-photo-1771383.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, quisquam.",
    price: 59,
    star: 5,
    username: "Audrey Richards",
  },
  {
    id: 6,
    img: "https://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
    pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, quisquam.",
    price: 79,
    star: 4,
    username: "Walton Shepard ",
  },
  {
    id: 7,
    img: "https://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
    pp: "https://images.pexels.com/photos/720606/pexels-photo-720606.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, quisquam.",
    price: 89,
    star: 5,
    username: "Waverly Schaefer",
  },
  {
    id: 8,
    img: "https://i0.wp.com/certicom.in/wp-content/uploads/2018/09/Income-Tax-Audit.jpg?w=700&ssl=1",
    pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, quisquam.r",
    price: 110,
    star: 4,
    username: "Wilton Hunt",
  },
];